#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Dec 28, 2022 09:16:51 AM JST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path
import subprocess as sb


local_v = open('virsion', 'r')
v = local_v.read()


sb.run(['wget', '-O', 'virsion on github', 'https://github.com/PEANUT-Sh/make-desktop/raw/main/virsion'])
git_v = open('virsion on github', 'r')
Gv = git_v.read()
os.remove('virsion on github')
print('Github上の最新バージョン' + Gv)
print('Latest version on Github' + Gv)
print('お使いのバージョン' + v)
print('Version in use' + v)

if (v == Gv):
    print('お使いのバージョンは最新です')
else:
    print('あなたのバージョン' + v + 'は最新ではありません')
    print(Gv + 'にアップデートできます')

check='wget -o gitV https://raw.githubusercontent.com/PEANUT-Sh/make-desktop/main/v.txt'


_script = sys.argv[0]
_location = os.path.dirname(_script)

import about_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x450+687+222")
        top.minsize(1, 1)
        top.maxsize(1905, 1050)
        top.resizable(1,  1)
        top.title("Toplevel 0")

        self.top = top

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.167, rely=0.133, height=25, width=409)
        self.Label1.configure(anchor='w')
        self.Label1.configure(compound='left')
        self.Label1.configure(cursor="arrow")
        self.Label1.configure(font="-family {Noto Sans CJK JP} -size 19")
        self.Label1.configure(text='''デスクトップファイル生成について''')
        self.Label2 = tk.Label(self.top)
        self.Label2.place(relx=0.183, rely=0.311, height=25, width=359)
        self.Label2.configure(anchor='w')
        self.Label2.configure(compound='left')
        self.Label2.configure(text='''簡単に.desktopファイルを生成するためのソフトウエア。''')
        self.Label3 = tk.Label(self.top)
        self.Label3.place(relx=0.167, rely=0.556, height=25, width=99)
        self.Label3.configure(anchor='w')
        self.Label3.configure(compound='left')
        self.Label3.configure(text='''バージョン''')
        self.Label4 = tk.Label(self.top)
        self.Label4.place(relx=0.517, rely=0.556, height=25, width=99)
        self.Label4.configure(anchor='w')
        self.Label4.configure(compound='left')
        self.Label4.configure(cursor="fleur")
        self.Label4.configure(text=v)
        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.233, rely=1.178, relheight=0.167
                , relwidth=0.208)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Label5 = tk.Label(self.top)
        self.Label5.place(relx=0.167, rely=0.644, height=25, width=169)
        self.Label5.configure(anchor='w')
        self.Label5.configure(compound='left')
        self.Label5.configure(text='''利用可能な最新バージョン''')
        self.Label4_1 = tk.Label(self.top)
        self.Label4_1.place(relx=0.517, rely=0.644, height=25, width=99)
        self.Label4_1.configure(activebackground="#f9f9f9")
        self.Label4_1.configure(anchor='w')
        self.Label4_1.configure(compound='left')
        self.Label4_1.configure(text=Gv)

def start_up():
    about_support.main()

if __name__ == '__main__':
    about_support.main()




